baseurl = "https://eclipsefdn.github.io/openadx.eclipse.org/"
DefaultContentLanguage = "en"
title = "" 
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = ""
disableKinds = ["taxonomyTerm"]
themesDir = "node_modules/"

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "OpenADx is about an ecosystem. Each company/partner brings its specialized expertise into one or more of the ecosystem topic areas helping to create the most efficient tool chain possible and improve that toolchain over time."
  subtitle = ""
  seo_title_suffix = "| Eclipse openADx Working Group | The Eclipse Foundation"
  keywords = []
  logo = "images/openadx-logo.svg"
  styles = "css/styles.css"
  favicon = "images/adx-favicon.ico"
# share_img = ""
  gcse = "011805775785170369411:p3ec0igo0qq"
# subtheme = ""
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "Eclipse openADx Working Group"
  website = "https://openadx.eclipse.org/"
# email = "chris.guindon@eclipse-foundation.org"
# facebook = "eclipse.org"
# twitter = "EclipseFdn"
# youtube = "EclipseFdn"
# googleplus = "+Eclipse"
# linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 1

[[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 2

[[menu.main]]
    name = "Vision"
    url = "/vision/"
    weight = 3

[[menu.main]]
    name = "Technologies"
    url = "/technologies/"
    weight = 4

[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 5

[[menu.main]]
    name = "Working Group"
    url = "/working-group/"
    weight = 6

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 7
